[api]
url = https://api.marketaux.com/v1/news/all
key = lH1ljRgzIdA7eRbDOfEiwP71xUdrlrwwyjVWzX7v

[aws]
s3_bucket = your_s3_bucket_name
glue_job_name = your_glue_job_name
region = your_aws_region
access_key_id = your_aws_access_key_id
secret_access_key = your_aws_secret_access_key
session_token = your_aws_session_token

[database]
host = postgres
port = 5432
name = smnews
user = admin
password = password

[redis]
host = redis
port = 6379

[celery]
broker_url = redis://redis:6379/0
result_backend = db+postgresql://airflow:airflow@postgres/airflow